---
title: "Basic usage -- COMPLETE"
author: "Ricardo Olea"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Basic usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Malleco data

It has has AR(1) structure.

```{r}
# y <- malleco
# op <- par(mfrow = c(1, 2), cex = 0.9)
# acf(y, lag = 10, ylim = c(-0.1, 1), bty = "n", las = 1, main = "")
# pacf(y, lag = 10, xlim = c(0, 10), ylim = c(-0.1, 1), bty = "n", las = 1, main = "")
# par(op)
```

```{r}
# y1 <- y[1:250]
# y2 <- y[243:492]
# y3 <- y[485:734]
# op <- par(mfrow = c(2, 3), cex = 0.9)
# acf(y1, lag = 10, ylim = c(-0.1, 1), bty = "n", las = 1, main = "block 1")
# acf(y2, lag = 10, ylim = c(-0.1, 1), bty = "n", las = 1, main = "block 2")
# acf(y3, lag = 10, ylim = c(-0.1, 1), bty = "n", las = 1, main = "block 3")
# pacf(y1, lag = 10, xlim = c(0, 10), ylim = c(-0.1, 1), bty = "n", las = 1, main = "")
# pacf(y2, lag = 10, xlim = c(0, 10), ylim = c(-0.1, 1), bty = "n", las = 1, main = "")
# pacf(y3, lag = 10, xlim = c(0, 10), ylim = c(-0.1, 1), bty = "n", las = 1, main = "")
# par(op)
```

## Analysis by blocks of phi and sigma parameters

```{r}
# block_smooth_periodogram(y, spar.freq = 0.8, spar.time = 0.8, theta = 90, phi = 0)
```

```{r}
# len_y <- length(y)
# N <- 200
# S <- 100
# M <- trunc((len_y - N) / S + 1)
# table <- c()
# for (j in 1:M) {
#   x <- y[(1 + S * (j - 1)):(N + S * (j - 1))]
#   table <- rbind(table, nlminb(
#     start = c(0.65, 0.15), N = N, objective = ls_whittle_loglik,
#     series = x, order = c(p = 1, q = 0)
#   )$par)
# }
# u <- (N / 2 + S * (1:M - 1)) / len_y
# table <- as.data.frame(cbind(u, table))
# colnames(table) <- c("u", "phi", "sigma")
# 
# op <- par(mfrow = c(1, 2), cex = 0.8)
# spar <- 0.6
# plot(smooth.spline(phi, spar = spar)$y ~ u,
#   data = table, pch = 20, ylim = c(0, 1),
#   xlim = c(0, 1), las = 1, bty = "n", ylab = expression(phi(u))
# )
# plot(smooth.spline(sigma, spar = spar)$y ~ u,
#   data = table, pch = 20, ylim = c(0, 0.2),
#   xlim = c(0, 1), las = 1, bty = "n", ylab = expression(phi(u))
# )
# par(op)
```

## Start parameters

```{r}
# phi <- smooth.spline(table$phi, spar = spar)$y
# fit.1 <- nls(phi ~ a0 + a1 * u, start = list(a0 = 0.65, a1 = 0.00))
# sigma <- smooth.spline(table$sigma, spar = spar)$y
# fit.2 <- nls(sigma ~ b0 + b1 * u, start = list(b0 = 0.65, b1 = 0.00))
# 
# fit <- ls_whittle(
#   series = y, start = c(coef(fit.1), coef(fit.2)), order = c(p = 1, q = 0),
#   ar.order = c(1), sd.order = 1, N = 180, n.ahead = 10
# )
```
